version: '1'
services:
  product:
    image: product:1.0.0
    container_name: product
    ports:
      - "8080:8080"
    networks:
      - fintech
  user:
    image: user:1.0.0
    container_name: user
    ports:
      - "8081:8081"
    networks:
      - fintech
  nginx:
    image: nginx:1.0.0
    container_name: nginx
    ports:
      - "8085:8085"
    networks:
      - fintech

networks:
  fintech:
    driver: bridge